<?php
if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group( array(
          'key' => 'group_65ef28a495cdb',
          'title' => 'B | Speaker Grip',
          'fields' => array(
               array(
                    'key' => 'field_65ef28a4492d7',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
               ),
               array(
                    'key' => 'field_65ef28b9492d8',
                    'label' => 'Speakers',
                    'name' => 'speakers',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => 'field_65ef28dc492d9',
                    'button_label' => 'Add Speaker',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                         array(
                              'key' => 'field_65ef28fa492db',
                              'label' => 'Portait',
                              'name' => 'portait',
                              'aria-label' => '',
                              'type' => 'image',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'return_format' => 'url',
                              'library' => 'all',
                              'min_width' => '',
                              'min_height' => '',
                              'min_size' => '',
                              'max_width' => '',
                              'max_height' => '',
                              'max_size' => '',
                              'mime_types' => '',
                              'preview_size' => 'medium',
                              'parent_repeater' => 'field_65ef28b9492d8',
                         ),
                         array(
                              'key' => 'field_65ef28dc492d9',
                              'label' => 'Speaker Name',
                              'name' => 'speaker_name',
                              'aria-label' => '',
                              'type' => 'text',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'placeholder' => '',
                              'prepend' => '',
                              'append' => '',
                              'parent_repeater' => 'field_65ef28b9492d8',
                         ),
                         array(
                              'key' => 'field_65ef28e4492da',
                              'label' => 'Speaker Function',
                              'name' => 'speaker_function',
                              'aria-label' => '',
                              'type' => 'text',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'placeholder' => '',
                              'prepend' => '',
                              'append' => '',
                              'parent_repeater' => 'field_65ef28b9492d8',
                         ),
                         array(
                              'key' => 'field_65ef2918492dc',
                              'label' => 'CV',
                              'name' => 'cv',
                              'aria-label' => '',
                              'type' => 'textarea',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'rows' => 6,
                              'placeholder' => '',
                              'new_lines' => '',
                              'parent_repeater' => 'field_65ef28b9492d8',
                         ),
                         array(
                              'key' => 'field_65f1b98c90be3',
                              'label' => 'LinkedIn',
                              'name' => 'linkedin',
                              'aria-label' => '',
                              'type' => 'url',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'placeholder' => '',
                         ),
                    ),
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'block',
                         'operator' => '==',
                         'value' => 'acf/speaker-grid',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
          'show_in_rest' => 0,
     ) ) ;
endif;
