<?php
if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group( array(
          'key' => 'group_6655d6150627b',
          'title' => 'B | Working Group',
          'fields' => array(
               array(
                    'key' => 'field_6655d6153d28d',
                    'label' => 'Poster',
                    'name' => 'poster',
                    'aria-label' => '',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '30',
                         'class' => '',
                         'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'preview_size' => 'medium',
               ),
               array(
                    'key' => 'field_6655d65e3d28e',
                    'label' => 'Content',
                    'name' => 'content',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '60',
                         'class' => '',
                         'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                         array(
                              'key' => 'field_6655d66e3d28f',
                              'label' => 'Title',
                              'name' => 'title',
                              'aria-label' => '',
                              'type' => 'text',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'placeholder' => '',
                              'prepend' => '',
                              'append' => '',
                         ),
                         array(
                              'key' => 'field_6655d6813d290',
                              'label' => 'Description',
                              'name' => 'description',
                              'aria-label' => '',
                              'type' => 'textarea',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'rows' => 4,
                              'placeholder' => '',
                              'new_lines' => '',
                         ),
                         array(
                              'key' => 'field_6655d6c43d291',
                              'label' => 'Leader',
                              'name' => 'leader',
                              'aria-label' => '',
                              'type' => 'group',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'layout' => 'block',
                              'sub_fields' => array(
                                   array(
                                        'key' => 'field_6655d6cf3d292',
                                        'label' => 'Firstname',
                                        'name' => 'firstname',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '50',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                   ),
                                   array(
                                        'key' => 'field_6655d6e23d293',
                                        'label' => 'Lastname',
                                        'name' => 'lastname',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '50',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                   ),
                                   array(
                                        'key' => 'field_6655d6fd3d295',
                                        'label' => 'Portrait',
                                        'name' => 'portrait',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '20',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'thumbnail',
                                   ),
                                   array(
                                        'key' => 'field_6655d6ed3d294',
                                        'label' => 'Company',
                                        'name' => 'company',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                             'width' => '80',
                                             'class' => '',
                                             'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                   ),
                              ),
                         ),
                    ),
               ),
               array(
                    'key' => 'field_6655d76d3d296',
                    'label' => 'Poster File',
                    'name' => 'poster_file',
                    'aria-label' => '',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'block',
                         'operator' => '==',
                         'value' => 'acf/working-group',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
          'show_in_rest' => 0,
     ) );
endif;
