<?php
if( function_exists('acf_add_local_field_group') ):

     acf_add_local_field_group( array(
          'key' => 'group_659d5899b4493',
          'title' => 'B | Boxes',
          'fields' => array(
               array(
                    'key' => 'field_659d58992c7a3',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
               ),
               array(
                    'key' => 'field_659d58a72c7a4',
                    'label' => 'Boxes',
                    'name' => 'boxes',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                         'width' => '',
                         'class' => '',
                         'id' => '',
                    ),
                    'layout' => 'block',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Eintrag hinzufügen',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                         array(
                              'key' => 'field_659d58be2c7a5',
                              'label' => 'Icon',
                              'name' => 'icon',
                              'aria-label' => '',
                              'type' => 'image',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'return_format' => 'url',
                              'library' => 'all',
                              'min_width' => '',
                              'min_height' => '',
                              'min_size' => '',
                              'max_width' => '',
                              'max_height' => '',
                              'max_size' => '',
                              'mime_types' => '',
                              'preview_size' => 'medium',
                              'parent_repeater' => 'field_659d58a72c7a4',
                         ),
                         array(
                              'key' => 'field_659d58ce2c7a6',
                              'label' => 'Box Title',
                              'name' => 'box_title',
                              'aria-label' => '',
                              'type' => 'text',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'maxlength' => '',
                              'placeholder' => '',
                              'prepend' => '',
                              'append' => '',
                              'parent_repeater' => 'field_659d58a72c7a4',
                         ),
                         array(
                              'key' => 'field_659d58d92c7a7',
                              'label' => 'Box Content',
                              'name' => 'box_content',
                              'aria-label' => '',
                              'type' => 'wysiwyg',
                              'instructions' => '',
                              'required' => 0,
                              'conditional_logic' => 0,
                              'wrapper' => array(
                                   'width' => '',
                                   'class' => '',
                                   'id' => '',
                              ),
                              'default_value' => '',
                              'tabs' => 'all',
                              'toolbar' => 'basic',
                              'media_upload' => 0,
                              'delay' => 0,
                              'parent_repeater' => 'field_659d58a72c7a4',
                         ),
                    ),
               ),
          ),
          'location' => array(
               array(
                    array(
                         'param' => 'block',
                         'operator' => '==',
                         'value' => 'acf/boxes',
                    ),
               ),
          ),
          'menu_order' => 0,
          'position' => 'normal',
          'style' => 'default',
          'label_placement' => 'top',
          'instruction_placement' => 'label',
          'hide_on_screen' => '',
          'active' => true,
          'description' => '',
          'show_in_rest' => 0,
     ) );
     
     endif;		